name = "maintenance"
main = "_worker.js"  # Keep this line, pointing to your empty worker
compatibility_date = "2025-01-15"

# Remove the entire [build] section:
# [build]
#   command = ""

# [build.upload]
#   format = "modules"
#   dir = "."
#   main = "_worker.js"